<?php

/** Databáza Menu **/

$meals = array(

            array(
                "number" => 10,
                "viet_name" => "Cơm Vịt Xạo",
                "sk_name" => "Jasmínová ryža s kačacím mäsom",
                "meat" => "🦆",
                "price" => "7",
                "side" => "🍚",
                "ingredients" => false,
        ),

            array(
                "number" => 11,
                "viet_name" => "Cơm Bò Xào Đỏ",
                "sk_name" => "Jasmínová ryža s hovädzým mäsom a lúskami",
                "meat" => "🐄",
                "price" => "6.5",
                "side" => "🍚",
                "ingredients" => false,
        ),

            array(
                "number" => 12,
                "viet_name" => "Cơm Bò Xào Sả Ót",
                "sk_name" => "Jasmínová ryža s hovädzím mäsom s chili a citrónovou trávou",
                "meat" => "🐄",
                "price" => "6.5",
                "side" => "🍚",
                "ingredients" => false,
        ),

            array(
                "number" => 13,
                "viet_name" => "Cơm Đáu Phụ",
                "sk_name" => "Jasmínová ryža s tofu",
                "meat" => "∅",
                "price" => "4.5",
                "side" => "🍚",
                "ingredients" => false,
        ),

            array(
                "number" => 14,
                "viet_name" => "Cơm Bò Xào Su Su",
                "sk_name" => "Jasmínová ryža s hovädzím mäsom a chouchou",
                "meat" => "🐄",
                "price" => "6.5",
                "side" => "🍚",
                "ingredients" => false,
        ),

            array(
                "number" => 15,
                "viet_name" => "Cơm Bò Xào Dúa",
                "sk_name" => "Jasmínová ryža s hovädzým mäsom a ananásom",
                "meat" => "🐄",
                "price" => "6.5",
                "side" => "🍚",
                "ingredients" => false,
        ),

            array(
                "number" => 16,
                "viet_name" => "Bún Xào",
                "sk_name" => "Ryžové rezance s mäsom",
                "meat" => "🐔 alebo 🐄",
                "price" => "6.0",
                "side" => "🍜",
                "ingredients" => array ( "Opekané ryžové rezance", "mäso", "vajce", "zelenina", "klíčky"),
        ),

            array(
                "number" => 17,
                "viet_name" => "Bún Xào Tôm",
                "sk_name" => "Ryžové rezance s krevetami",
                "meat" => "🦐",
                "price" => "6",
                "side" => "🍜",
                "ingredients" => false,
        ),

            array(
                "number" => 18,
                "viet_name" => "Nem Rán",
                "sk_name" => "Vyprážené rolky",
                "meat" => "🐖",
                "price" => "4",
                "side" => "🍜",
                "ingredients" => array ( "Bravčové mäso", "huby", "vajce", "zeleniana", "číre rezance", "korenie"),
        ),

            array(
                "number" => 19,
                "viet_name" => "Cơm Bò Xào Cài",
                "sk_name" => "Jasmínová ryža s hovädzím mäsom a pak-choi kapustou",
                "meat" => "🐄",
                "price" => "6.5",
                "side" => "🍚",
                "ingredients" => false,
        ),  
           
            array(
                "number" => 20,
                "viet_name" => "Nem Cuón",
                "sk_name" => "Čerstvé rolky",
                "meat" => "🦐",
                "price" => "5",
                "side" => "🍜",
                "ingredients" => array ( "Ryžové rezance", "krevety", "zelenina", "ryžový papier", "pikantno-sladkokyslá rybacia omáčka"),
        ),                 
            array(
                "number" => 21,
                "viet_name" => "Vịt Dòn",
                "sk_name" => "Chrumkavá kačica",
                "meat" => "🦆",
                "price" => "4.8",
                "side" => false,
                "ingredients" => array ( "Kačacie prsia", "korenie", "šalát", "omáčka"),
        ),                 
            array(
                "number" => 22,
                "viet_name" => "Gà Dòn",
                "sk_name" => "Chrumkavé kura",
                "meat" => "🐔",
                "price" => "3.8",
                "side" => false,
                "ingredients" => array ( "Kuracie prsia", "korenie", "šalát", "omáčka"),
        ),                 
            array(
                "number" => 23,
                "viet_name" => "Bún Chả",
                "sk_name" => "Grilované mäso a ryžové rezance",
                "meat" => "🐖",
                "price" => "5.5",
                "side" => "🍜",
                "ingredients" => array ( "Grilované bravčové mäso", "sójové klíčky", "pikantno-sladkokyslá rybacia omáčka", "vietnamské bylinky", "šarlotky", "ryžové rezance"),
        ),                 
            array(
                "number" => 24,
                "viet_name" => "Bún Nem",
                "sk_name" => "Vyprážené rolky a ryžové rezance",
                "meat" => false,
                "price" => "5",
                "side" => "🍜",
                "ingredients" => array ( "Vyprážené rolky", "sójové klíčky", "pikantno-sladkokyslá omáčka", "vietnamské bylinky", "šalotky", "ryžné rezance"),
        ),                 
            array(
                "number" => 25,
                "viet_name" => "Bún Chả Lá Lôt",
                "sk_name" => "Grilované fašírky v liste a ryžové rezance",
                "meat" => false,
                "price" => "6",
                "side" => "🍜",
                "ingredients" => array ( "Grilované fašírky v liste", "sójové klíčky", "pikantno-sladkokyslá omáčka", "vietnamské bylinky", "šalotky", "ryžové rezance"),
        ),                 
            array(
                "number" => 26,
                "viet_name" => "Bún Bò Nam Bộ",
                "sk_name" => "Juhovietnamské rezance hovädzie",
                "meat" => "🐄",
                "price" => "5.8",
                "side" => "🍜",
                "ingredients" => array ( "Restované hovädzie mäso", "sójové klíčky", "vietnamské bylinky", "arašidy", "šalotky", "pikantno-sladkokyslá rybacia omáčka"),
        ),                 
            array(
                "number" => 27,
                "viet_name" => "Bún Chả Chan",
                "sk_name" => "Ryžová rezancová polievka s grilovaným mäsom",
                "meat" => false,
                "price" => "5.5",
                "side" => "🍜",
                "ingredients" => array ( "Grilované mäso", "ryžové rezance", "koriander", "cibuľky", "sójové klíčky", "bylinky", "vývar zo špikových kostí"),
        ),                 
            array(
                "number" => 28,
                "viet_name" => "Bún Chả Cá",
                "sk_name" => "Ryžová rezancová polievka s rybacími fašírkami",
                "meat" => "🐟",
                "price" => "6.5",
                "side" => "🍜",
                "ingredients" => array ( "Rybacie fašírky", "ryžové rezance", "koriander", "cibuľky", "sójové klíčky", "bylinky", "vývar zo špikových kostí"),
        ),                 
/*            array(
                "number" => 29,
                "viet_name" => "",
                "sk_name" => "",
                "meat" => "X",
                "price" => "X",
                "side" => "X",
                "ingredients" => array ( "Opekané ryžové rezance", "mäso", "vajce", "zelenina", "klíčky"),
        ), */      
            array(
                "number" => 30,
                "viet_name" => "Cơm Thịt Nướng",
                "sk_name" => "Jasmínová ryža s grilovaným mäsom",
                "meat" => "🦆 alebo 🐄",
                "price" => "7.5",
                "side" => "🍚",
                "ingredients" => false,
        ),      
            array(
                "number" => 31,
                "viet_name" => "Bún Chả Cá",
                "sk_name" => "Vyprážené rybacie fašírky a ryžové rezance",
                "meat" => "🐟",
                "price" => "6",
                "side" => "🍜",
                "ingredients" => array ( "Rybacie fašírky", "sójové klíčky", "pikantno-sladkokyslá omáčka", "vietnamské bylinky", "šalotky", "ryžové rezance"),
        ),     
            array(
                "number" => 32,
                "viet_name" => "Phở",
                "sk_name" => "Vietnamská rezancová polievka",
                "meat" => "🐔 alebo 🐄",
                "price" => "4.3",
                "side" => false,
                "ingredients" => array ( "Vývar zo špikových kostí", "badián", "škorica", "zázvor", "korenie", "mäso", "ryžové široké rezance", "koriander", "cibuľky"),
        ),     
            array(
                "number" => 33,
                "viet_name" => "Miến Ngan Trộn",
                "sk_name" => "Vietnamské číre rezance s kačacím mäsom",
                "meat" => "🦆",
                "price" => "6.5",
                "side" => "🍜",
                "ingredients" => array ( "Kačacie mäso", "číre rezance", "koriander", "cibuľky", "sójové klíčky", "bylinky", "arašidy", "sladkokyslá omáčka"),
        ),     
            array(
                "number" => 34,
                "viet_name" => "Miến Ngan",
                "sk_name" => "Vietnamské číro-rezancová polievka s kačacím mäsom",
                "meat" => "🦆",
                "price" => "6",
                "side" => "🍜",
                "ingredients" => array (  "Kačacie mäso", "číre rezance", "koriander", "cibuľky", "sójové klíčky", "bylinky", "vývar zo špikových kostí"),
        ),     
            array(
                "number" => 35,
                "viet_name" => "Bún Tôm",
                "sk_name" => "Ryžová rezancová polievka s krevatami",
                "meat" => "🦐",
                "price" => "6.5",
                "side" => false,
                "ingredients" => array ( "Krevety", "ryžové rezance", "koriander", "cibuľky", "sójové klíčky", "bylinky", "vývar zo špikových kostí"),
        ),     
            array(
                "number" => 36,
                "viet_name" => "Cơm Tôm Thịt Bò",
                "sk_name" => "Jasmínová ryža s krevetami a hovädzým mäsom",
                "meat" => "🦐 a 🐄",
                "price" => "7.5",
                "side" => "🍚",
                "ingredients" => false,
        ),     
/*            array(
                "number" => "",
                "viet_name" => "",
                "sk_name" => "",
                "meat" => "X",
                "price" => "X",
                "side" => "X",
                "ingredients" => array ( "Opekané ryžové rezance", "mäso", "vajce", "zelenina", "klíčky"),
        ),  */   
            array(
                "number" => 38,
                "viet_name" => "Phở Mix",
                "sk_name" => "Vietnamská polievka s mix hovädzím a kuracím mäsom",
                "meat" => "🐔 a 🐄",
                "price" => "5.5",
                "side" => false,
                "ingredients" => array ( "Vývar zo špikových kostí", "badián", "škorica", "zázvor", "korenie", "mäso", "ryžové široké rezance", "koriander", "cibuľky"),
        ),                
            array(
                "number" => 39,
                "viet_name" => "Bún Xào Rau",
                "sk_name" => "Ryžové rezance so zeleninou",
                "meat" => "∅",
                "price" => "3.5",
                "side" => "🍜",
                "ingredients" => false,
        ),                
/*            array(
                "number" => "",
                "viet_name" => "",
                "sk_name" => "",
                "meat" => "X",
                "price" => "X",
                "side" => "X",
                "ingredients" => array ( "Opekané ryžové rezance", "mäso", "vajce", "zelenina", "klíčky"),
        ),   */             
            array(
                "number" => 48,
                "viet_name" => "Cơm Tôm Thịt Bãm Rán",
                "sk_name" => "Jasmínová ryža s obaľovanými krevetami a mletým mäsom",
                "meat" => "🦐 a zmäs mäsa",
                "price" => "7",
                "side" => "🍚",
                "ingredients" => false,
        ),                
            array(
                "number" => 49,
                "viet_name" => "Cơm Thịt Nướng",
                "sk_name" => "Jasmínová ryža s grilovaným mäsom",
                "meat" => "🦆 alebo 🐄",
                "price" => "7.5",
                "side" => "🍚",
                "ingredients" => false,
        ),                
            array(
                "number" => 50,
                "viet_name" => "Cơm Gà Zảo Rau",
                "sk_name" => "Jasmínová ryža s kuracím mäsom a zeleninou",
                "meat" => "🐔",
                "price" => "5",
                "side" => "🍚",
                "ingredients" => false,
        ),                
            array(
                "number" => 51,
                "viet_name" => false,
                "sk_name" => "Menu pre štyroch ľudí",
                "meat" => "zmäs mäsa",
                "price" => "36",
                "side" => false,
                "ingredients" => array ( "Smažený bôčik", "Grilované mleté mäso v Piper Lolot liste", "Grilované mäso", "Smažené krevety"),
        ),
);       
?>